# Generated by Django 4.2 on 2023-04-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='dollar_equivalent',
        ),
        migrations.AddField(
            model_name='currency',
            name='convertion_rate',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
