# Generated by Django 4.2 on 2023-04-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0004_alter_category_name_alter_subcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
