# Generated by Django 4.2 on 2023-05-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0007_alter_currency_last_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='account_type',
            field=models.CharField(choices=[('General', 'General'), ('Cash', 'Cash'), ('Credit card', 'Credit card')], default='General', max_length=20),
        ),
        migrations.AddField(
            model_name='wallet',
            name='color',
            field=models.CharField(default='#1565c0', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='exclude_from_statistic',
            field=models.BooleanField(default=False),
        ),
    ]
